[package]
name = "reaper_gojira_dll"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
c_str_macro = "1.0.3"
crossbeam-channel = "0.5.12"
rand = "0.8.5"
reaper-low = "0.1.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
ws = "0.9.2"

