[package]
name = "gojira_brain_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.12"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
ws = "0.9.2"

